### PR TITLE
Rendering fix

### PR DESCRIPTION
**Pull request by darthLeviN**
- Small bugfixes.
- The transparency of some objects and the flicker of the piano letters was fixed. 
- The color correctness that makes colors appear dimmer on web export was fixed with a gradient as workaround.

multiplying values that are tagged as "source_color" together seems to give stable results. but doing any sort of custom math on them will result in inconsistency.

### CODE REVIEW

**Review by LobsterUberlord — COMMENTED** [review]
I don't see any of these blue boxes representing notes in the web export. Only see them when I run the game in the editor.

image

**Comment by darthLeviN** [comment]
> I don't see any of these blue boxes representing notes in the web export. Only see them when I run the game in the editor.
> 
> image

I don't know why this is happening. i have the notes. can you send a log or smth? and also tell me what browser and OS you're using.
If it's a separate issue i'm gonna have to fix that separately. It's possible the notes aren't spawning.  Because the notes seem to be just opaque unshaded meshes. there is nothing special about them.

Screenshot_20230208_094007

**Comment by LobsterUberlord** [comment]
I'm testing this on Chrome 109.0.5414.120 on Windows 10.
Browser console shows a couple of tween errors, not sure if relevant:

```
﻿Godot Engine v4.0.beta16.official.518b9e580 - https://godotengine.org
lam.js:13976 OpenGL Renderer: WebKit WebGL
lam.js:13976  
lam.js:13991 Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
lam.js:13991 USER SCRIPT ERROR: Parse Error: Not all code paths return a value.
lam.js:13991    at: GDScript::reload (res://scenes/song_parser/chord.gd:60)
lam.js:13976 Instruments configured :["piano.tres", "guitar.tres"]
lam.js:13976 finished loading config

lam.js:13991 USER ERROR: MIDI input isn't supported on Web.
lam.js:13991    at: open_midi_inputs (core/os/os.cpp:509)

lam.js:13976 ConnectionStatusLabel:<Label#80077653469>
lam.js:13976 === Nakama : DEBUG === Sending request

lam.js:13991 USER ERROR: Couldn't open directory at path "user://songs".
lam.js:13991    at: get_directories_at (core/io/dir_access.cpp:505)
lam.js:13991 USER ERROR: Couldn't open directory at path "user://songs".
lam.js:13991    at: get_files_at (core/io/dir_access.cpp:495)
lam.js:13991 USER ERROR: <Tween#-9223371939848911107>: started with no Tweeners.
lam.js:13991    at: step (scene/animation/tween.cpp:291)

lam.js:13976 200
lam.js:13976 file [http://127.0.0.1:5173/songs.json] downloaded.
lam.js:13976 === Nakama : DEBUG === Freeing request 1
lam.js:13976 session.expired: false
lam.js:13976 session.expire_time: 1675880497
lam.js:13976 === Nakama : DEBUG === Connecting to host
lam.js:13976 Backend fully initialized.
lam.js:13976 200
lam.js:13976 file [http://127.0.0.1:5173/songs/Bruce-Springsteen_Tougher-Than-The-Rest_v1_RS2014_Pc/songs/arr/bubrucetough_lead.xml] downloaded.
lam.js:13976 XML Parser: Need to add linkedDiff data here, but no idea what that is yet
lam.js:13976 XML Parser: Need to add phraseProperty data here, but no idea what that is yet
lam.js:13976 XML Parser: Need to add fretHandMuteTemplate data here, but no idea what that is yet
lam.js:13976 XML Parser: Need to add transcription track data here, but no idea what the properties are yet
lam.js:13976 song [Tougher Than the Rest] added
7
[Violation] 'requestAnimationFrame' handler took <N>ms
lam.js:13976 Preloading song configurations completed.
lam.js:13976 Socket connected.
lam.js:13976 === Nakama : INFO === Connected!
GamePlayer.svelte? [sm]:113 resizing game canvas 
{width: 728, height: 485}
GamePlayer.svelte? [sm]:113 resizing game canvas 
{width: 1728, height: 1152}
[Violation] 'mouseup' handler took 1149ms
7
lam.js:13976 Added song: Tougher Than the Rest

lam.js:13991 USER ERROR: <Tween#-9223371566555836543>: started with no Tweeners.
lam.js:13991    at: step (scene/animation/tween.cpp:291)

lam.js:13976 reconfiguring camera for session instrument [piano.tres]
lam.js:13976 performance song changed to Tougher Than the Rest
lam.js:13976 loading song [Tougher Than the Rest] from [songs/Bruce-Springsteen_Tougher-Than-The-Rest_v1_RS2014_Pc/audio/windows/song_bubrucetough_fixed.ogg.mp3]
lam.js:13976 game finished!
lam.js:13976 200
lam.js:13976 file [http://127.0.0.1:5173/songs/Bruce-Springsteen_Tougher-Than-The-Rest_v1_RS2014_Pc/audio/windows/song_bubrucetough_fixed.ogg.mp3] downloaded.
lam.js:13976 loaded song [<RefCounted#-9223371706242941810>]
lam.js:13976 All clients seem to be ready.
lam.js:13976 Starting game
﻿```

**Review by LobsterUberlord — APPROVED** [review]

**Comment by darthLeviN** [comment]
> I'm testing this on Chrome 109.0.5414.120 on Windows 10. Browser console shows a couple of tween errors, not sure if relevant:
> 
> ```
> ﻿Godot Engine v4.0.beta16.official.518b9e580 - https://godotengine.org
> lam.js:13976 OpenGL Renderer: WebKit WebGL
> lam.js:13976  
> lam.js:13991 Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
> lam.js:13991 USER SCRIPT ERROR: Parse Error: Not all code paths return a value.
> lam.js:13991    at: GDScript::reload (res://scenes/song_parser/chord.gd:60)
> lam.js:13976 Instruments configured :["piano.tres", "guitar.tres"]
> lam.js:13976 finished loading config
> 
> lam.js:13991 USER ERROR: MIDI input isn't supported on Web.
> lam.js:13991    at: open_midi_inputs (core/os/os.cpp:509)
> 
> lam.js:13976 ConnectionStatusLabel:<Label#80077653469>
> lam.js:13976 === Nakama : DEBUG === Sending request
> 
> lam.js:13991 USER ERROR: Couldn't open directory at path "user://songs".
> lam.js:13991    at: get_directories_at (core/io/dir_access.cpp:505)
> lam.js:13991 USER ERROR: Couldn't open directory at path "user://songs".
> lam.js:13991    at: get_files_at (core/io/dir_access.cpp:495)
> lam.js:13991 USER ERROR: <Tween#-9223371939848911107>: started with no Tweeners.
> lam.js:13991    at: step (scene/animation/tween.cpp:291)
> 
> lam.js:13976 200
> lam.js:13976 file [http://127.0.0.1:5173/songs.json] downloaded.
> lam.js:13976 === Nakama : DEBUG === Freeing request 1
> lam.js:13976 session.expired: false
> lam.js:13976 session.expire_time: 1675880497
> lam.js:13976 === Nakama : DEBUG === Connecting to host
> lam.js:13976 Backend fully initialized.
> lam.js:13976 200
> lam.js:13976 file [http://127.0.0.1:5173/songs/Bruce-Springsteen_Tougher-Than-The-Rest_v1_RS2014_Pc/songs/arr/bubrucetough_lead.xml] downloaded.
> lam.js:13976 XML Parser: Need to add linkedDiff data here, but no idea what that is yet
> lam.js:13976 XML Parser: Need to add phraseProperty data here, but no idea what that is yet
> lam.js:13976 XML Parser: Need to add fretHandMuteTemplate data here, but no idea what that is yet
> lam.js:13976 XML Parser: Need to add transcription track data here, but no idea what the properties are yet
> lam.js:13976 song [Tougher Than the Rest] added
> 7
> [Violation] 'requestAnimationFrame' handler took <N>ms
> lam.js:13976 Preloading song configurations completed.
> lam.js:13976 Socket connected.
> lam.js:13976 === Nakama : INFO === Connected!
> GamePlayer.svelte? [sm]:113 resizing game canvas 
> {width: 728, height: 485}
> GamePlayer.svelte? [sm]:113 resizing game canvas 
> {width: 1728, height: 1152}
> [Violation] 'mouseup' handler took 1149ms
> 7
> lam.js:13976 Added song: Tougher Than the Rest
> 
> lam.js:13991 USER ERROR: <Tween#-9223371566555836543>: started with no Tweeners.
> lam.js:13991    at: step (scene/animation/tween.cpp:291)
> 
> lam.js:13976 reconfiguring camera for session instrument [piano.tres]
> lam.js:13976 performance song changed to Tougher Than the Rest
> lam.js:13976 loading song [Tougher Than the Rest] from [songs/Bruce-Springsteen_Tougher-Than-The-Rest_v1_RS2014_Pc/audio/windows/song_bubrucetough_fixed.ogg.mp3]
> lam.js:13976 game finished!
> lam.js:13976 200
> lam.js:13976 file [http://127.0.0.1:5173/songs/Bruce-Springsteen_Tougher-Than-The-Rest_v1_RS2014_Pc/audio/windows/song_bubrucetough_fixed.ogg.mp3] downloaded.
> lam.js:13976 loaded song [<RefCounted#-9223371706242941810>]
> lam.js:13976 All clients seem to be ready.
> lam.js:13976 Starting game
> ﻿```
> ```

Going to make a different PR to fix it.

**Pull request merged**
